# Generated by Django 5.2.13 on 2026-04-14 23:28

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_default_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyagmaccounts',
            name='summary_json',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='monthlymetrics',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
