# Generated by Django 5.2.13 on 2026-05-10 09:38

from django.db import migrations, models


def forwards_migrate_upload_status(apps, schema_editor):
    Upload = apps.get_model('accounting', 'BankStatementUpload')
    BankTransaction = apps.get_model('accounting', 'BankTransaction')
    MonthlyAGMAccounts = apps.get_model('accounting', 'MonthlyAGMAccounts')
    for upload in Upload.objects.all():
        labelled = BankTransaction.objects.filter(
            upload_id=upload.id,
        ).exclude(label_id__isnull=True).count()
        upload.auto_labelled_count = labelled
        if not getattr(upload, 'processed', False):
            upload.status = 'processing'
        elif MonthlyAGMAccounts.objects.filter(month=upload.month).exists():
            upload.status = 'processed'
        else:
            upload.status = 'automatically_labelled'
        upload.save(update_fields=['auto_labelled_count', 'status'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_bankstatementupload_signed_debit_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementupload',
            name='auto_labelled_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bankstatementupload',
            name='status',
            field=models.CharField(
                choices=[
                    ('processing', 'Processing'),
                    ('automatically_labelled', 'Automatically labelled'),
                    ('processed', 'Processed'),
                ],
                default='processing',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bookmark',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', '—'),
                    ('unsure', 'Unsure'),
                    ('check', 'Check'),
                    ('missing_receipt', 'Missing receipt'),
                ],
                default='',
                max_length=24,
            ),
        ),
        migrations.RunPython(forwards_migrate_upload_status, noop_reverse),
        migrations.RemoveField(
            model_name='bankstatementupload',
            name='processed',
        ),
    ]
